export const FETCH_BOOKING_SUCCESS = 'FETCH_BOOKING_SUCCESS'
export const FETCH_BOOKING_START = 'FETCH_BOOKING_START'
export const FETCH_BOOKING_FAIL = 'FETCH_BOOKING_FAIL'

export const SELECT_FLIGHT = 'SELECT_FLIGHT'
export const UNSELECT_FLIGHT = 'UNSELECT_FLIGHT'

export const SELECT_MEAL = 'SELECT_MEAL'
export const UNSELECT_MEAL = 'UNSELECT_MEAL'

export const OFFER_MEAL = 'OFFER_MEAL'
export const CANCEL_OFFER_MEAL = 'CANCEL_OFFER_MEAL'
